apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc     
spec:
  replicas: 3
  selector:
    app: ngnix
  template:
    metadata:
      name: ngnix
      labels:
        app: ngnix      
    spec:
      containers:
      - name: ngniximage
        image: ngnix
        ports:
        - containerPort: 80
