apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
spec:
  replicas: 4   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector: 
    matchLabels:
      app: openmrs
  template:
    metadata:
        labels:
          app: openmrs
  
    spec:
        containers:
          - name: openmrscustomimage
            image: shefalisardana/openmrs_customimage:1 
            ports:
             - containerPort: 80    

    
